### ISSUE TITLE
The latest version of camtronis not unzipping

### ISSUE THREAD

**Issue by MeghrajBhanu** [vee2xx/camtron#1]
Hey there , I have tried using your code for one of my app and it wasn't working, I looked into it and found that you are downloading a binary from latest releases .

To debug I have tried your demo app ,the binary is downloading but its not in correct format and its not unzipping so i have replaced the file with a stable release locally.

Now the camtron seems to work.

**Comment by vee2xx** [comment]
Hey! Thanks for the comment! I had issues with zipping the UI release for Mac and Windows on Ubuntu and I think one of these bad packages got uploaded. I am going to look into it shortly,

Thanks again for the helpful feedback. Let me know if you run into any more problems.

**Comment by vee2xx** [comment]
I made a new release and uploaded new binaries. The current version of Camtron should automatically download them. Let me know if they don't unzip. I tested on Windows, Mac and Ubuntu 18. What OS are you using?

**Comment by MeghrajBhanu** [comment]
Thanks for the update!

I will definitely try it, I'm releasing my app for all the os versions ,but as of know I have tested it only for windows.
